version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - net-local
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
      
     
  
  loyalty:
    build:
      context: ./src/lab2/Loyalty Service/
      dockerfile: Dockerfile
    restart: always
    container_name: loyalty_lab3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    networks:
      - net-local
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8050/manage/health"]
      interval: 5s
      timeout: 10s
      
  payment:
    build:
      context: ./src/lab2/Payment Service/
      dockerfile: Dockerfile
    restart: always
    container_name: payment_lab3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8060:8060"
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    networks:
      - net-local
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8060/manage/health"]
      interval: 5s
      timeout: 10s
  reservation:
    build:
      context: ./src/lab2/Reservation Service/
      dockerfile: Dockerfile
    restart: always
    container_name: reservation_lab3
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8070"
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    networks:
      - net-local
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8070/manage/health"]
      interval: 5s
      timeout: 10s
      
  gateway:
    build:
      context: ./src/lab2/Gateway/
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - reservation
      - payment
      - loyalty
    networks:
      - net-local

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/manage/health"]
      interval: 5s
      timeout: 10s
    
  
networks:
  net-local:
    driver: bridge